### ISSUE TITLE
New gophernotes maintainer, help wanted

### ISSUE THREAD

**Issue by dwhitena** [gopherdata/gophernotes#112]
Hi all. I'm having quite a bit of trouble finding the time needed to maintain this project. I appreciate the recent interest and work, and I apologize for taking so long to review PRs and issues. However, I definitely want to see the project move forward, improve, and make an impact.

Would anyone in this community be up for acting as the primary maintainer (reviewing PRs, looking into reported issues, etc.)? Maybe someone who is invested and contributing lately like @SpencerPark @sbinet @cosmos72? Let me know and I will add you to the gopherdata org.

Thanks!

**Comment by cosmos72** [comment]
Many thanks for the offer @dwhitena, I am honoured :)

I was already thinking to propose a more active role from my part, and having write access to the project would surely facilitate me a lot in that.

My hands are a bit full at the moment, so I think a candidate with more free time would be preferrable, but if @SpencerPark and @sbinet decline (or are so busy that they do not reply) I will happily accept.

**Comment by sbinet** [comment]
Hi,
Right now, I can't shepherd another organization.
I can, probably, help.
But I can't lead. Sorry.

**Comment by SpencerPark** [comment]
I am happy to help when I have some free time but I don't think I would be able to keep up on my own either. Maybe a couple with write access would help balance the load? :)

**Comment by dwhitena** [comment]
@cosmos72 Looks like you are the most available at the moment. Thank you so much for your help on this! I really appreciate it. I'm going to send you an invite to the gopherdata org and get you write access here. Please let me know if you have questions, and feel free to start reviewing PRs, responding to things, etc.

**Comment by cosmos72** [comment]
Thanks a lot, it's an honour :)

I wouldn't mind if SpencerPark gets write access too - provided that he wants - in order to share the load.

**Comment by cosmos72** [comment]
I have a question, to clarify my position:
you expect me to act as gophernotes maintainer, update it, fix bugs, merge pull requests etc., or you want to do those yourselves?
Maybe I am simply being too scrupulous, but I am asking because you mentioned only **reviewing** PRs, not merging them.

**Comment by cosmos72** [comment]
Now that you granted write access to @SpencerPark, @sbinet and me, I'd say we can close this issue.
