### ISSUE TITLE
Interface definition should be insensitive to methods order

### ISSUE THREAD

**Issue by korewayume** [gopherdata/gophernotes#119]
version: v1.0.0-RC1
platform: mac 10.12.6
jupyter-lab -V
0.32.1
[gist](https://gist.github.com/korewayume/a2d639d5c8cf44f8a9d5b88336fdce37)

**Comment by cosmos72** [comment]
Yep, definitely a bug.

Thanks for spotting the problem, I will work on it in the next days.
For completeness, I opened a corresponding [gomacro issue](https://github.com/cosmos72/gomacro/issues/27)
