### ISSUE TITLE
Display should have an option to use WriterTo

### ISSUE THREAD

**Issue by btracey** [gopherdata/gophernotes#121]
As far as I can tell, this is currently the easiest way to display a gonum/plot

```
p, _ := plot.New()
p.Add(scat)
w, err := p.WriterTo(8*vg.Inch, 8*vg.Inch, "jpg")
if err != nil{
    panic(err)
}
var b bytes.Buffer
writer := bufio.NewWriter(&b)
w.WriteTo(writer)
display.JPEG(b.Bytes())
```

This is a lot of effort. It would be really nice if this could somehow be
`display.JPEGTo(p.WriterTo(8*vg.Inch, 8*vg.Inch, "jpg"))`

At the very least, it seems like `display` should be using the `io` interfaces instead of taking in a `[]byte` directly

**Comment by cosmos72** [comment]
Hi @btracey,
I agree, displaying a gonum/plot is cumbersome with the current API.
It would be nice to have something like
```
p, _ := plot.New()
// ...
img, err := p.Image(8*vg.Inch, 8*vg.Inch)
display.Image(img)
```
but I guess it will happen only if somebody implements that and gets it merged.

I am not very fond of duplicating the whole `display` API and a bunch of the functions
```
func JPEGTo(io.WriterTo) Data
func PNGTo(io.WriterTo) Data
func SVGTo(io.WriterTo) Data
func PDFTo(io.WriterTo) Data
...
```
also because they invite to add as well
```
func JPEGRead(io.Reader Data
func PNGRead(io.Reader) Data
func SVGRead(io.Reader) Data
func PDFRead(io.Reader) Data
...
```

What about adding instead only the two functions
```
func WriterTo(mimeType string, to io.WriterTo) Data
func Reader(mimeType string, r io.Reader) Data
```
?

**Comment by sbinet** [comment]
FYI, I introduced `hplot.Show` to achieve the same thing with the neugram jupyter kernel:
https://godoc.org/go-hep.org/x/hep/hplot#Show

so one would just have to run:
```go
hplot.Show(p, width, height, "png")
```
at the jupyter prompt.

**Comment by cosmos72** [comment]
Thanks @sbinet, you read my mind:
I was thinking about a function
```
display.Plot(p *plot.Plot, width vg.Length, height vg.Length)
```
although it has the unfortunate side effect that gonum.org/plot becomes a dependency of gophernotes

**Comment by sbinet** [comment]
it doesn't have to:

- `gonum/plot` could expose an interface, or
- `gophernotes` could make up an interface that `gonum/plot.Plot` would implicitly implement, or
- we could create a third-party package that binds everything together

also, note that the display implementation of `neugram` is using [net/http.DetectContentType](https://godoc.org/net/http#DetectContentType) to avoid having all the `display.JPEG`, `display.PNG`, ... methods.

**Comment by cosmos72** [comment]
I have added
```
func WriterTo(mimeType string, to io.WriterTo) Data
func Reader(mimeType string, r io.Reader) Data
```
to the package `display`, with mimeType autodetection as you suggested.
