### ISSUE TITLE
Can't get display to function in go notebook

### ISSUE THREAD

**Issue by dhruvkapur91** [gopherdata/gophernotes#124]
Hi.

I can't get the basic display command to function.
`display.HTML(<h1 style="color:green;">Hello, World</h1>)`

And I get:
`repl.go:1:1: undefined identifier: display`

This is after directly running:
`docker run -it -p 8888:8888 gopherdata/gophernotes`

I can get basic things to work, like defining variables, using fmt library etc.

**Comment by cosmos72** [comment]
Described more in detail in #125
