### ISSUE TITLE
Dockerhub doesn't seem to be updated with latest images/builds of gophernotes

### ISSUE THREAD

**Issue by dhruvkapur91** [gopherdata/gophernotes#125]
The page at [DockerHub](https://hub.docker.com/u/gopherdata/) seems to have images that are atleast 8 months old. Should push the new images in?

**Comment by cosmos72** [comment]
Yes, definitely.
But I currently don't know how to do that.
@dwhitena or @SpencerPark: any pointer?

**Comment by dhruvkapur91** [comment]
@cosmos72 

Yes. Travis-ci will be great way ahead.

We can run tests, if they pass publish a new version in the dockerhub.

**Comment by SpencerPark** [comment]
The automated build is now setup so `latest` on https://hub.docker.com/r/gopherdata/gophernotes/ _should_ stay up to date with master if things were set up correctly. The DS variant is tagged `latest-ds` and is now in the same repository as the main one. As a side effect of this whole setup the Dockerfiles were also fixed so they build again and shouldn't break when updates happen in the future so lets keep our fingers crossed!
