### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [gopherdata/gophernotes#129]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73 and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by cosmos72** [comment]
After examining the reported issue [satori/go.uuid#73](https://github.com/satori/go.uuid/issues/73) and the corresponding source code [satori/go.uuid/generator.go#L168](https://github.com/satori/go.uuid/blob/master/generator.go#L168) I agree it's a critical bug.

As a stop-gap, I am manually patching the vendored copy of `satori/go.uuid` included in gophernotes.

If a better (and more maintained) uuid library emerges, the switch is easy: gophernotes calls `uuid.NewV4()` in exactly **one** place
