### ISSUE TITLE
license: revert to MIT for ZMQ/JupyterLab communication layer

### ISSUE THREAD

**Issue by jdundondev** [gopherdata/gophernotes#130]
I work in a team at Teradata that is developing a JupyterLab kernel to execute SQL code. We are writing our kernel in Golang and would like to use the subset of Gophernotes that supports ZMQ/JupyterLab communications. Specifically we would like to use code from kernel.go and messages.go.
 
Teradata is requesting a change in license to the ZMQ/JupyterLab communication layer (kernel.go and messages.go) from Gophernotes (both current and later versions) to be under the MIT license.
 
This is related to #126, so if #126 is approved, that would clearly be a better solution. But we are entering a new issue for this smaller request because there are fewer contributors that would need to approve.
 
The contributors to kernel.go and messages.to that would need to approve are as follows: 
https://github.com/dwhitena
https://github.com/cosmos72
https://github.com/SpencerPark
https://github.com/QuLogic

Thanks for your consideration on this issue (or #126).

**Comment by dwhitena** [comment]
Any thoughts here @sbinet @cosmos72 or @SpencerPark?

**Comment by sbinet** [comment]
I'd err on trying to get https://github.com/gopherdata/gophernotes/issues/126 through (and a pure MIT `gophernotes`).

**Comment by cosmos72** [comment]
I agree to use the same license for all gophernotes code (not considering dependencies).

On the other hand, my taste on licenses is known (see #109). I will not oppose to MIT if there is agreement on it, but I am not going to advocate for it

**Comment by sbinet** [comment]
Everything in gophernotes is back to being MIT :)

(Note that now that it's MIT again, I will probably contribute my pure-Go zeroMQ implementation of the Jupyter kernel messaging layer. Perhaps this could be done in a separate repo/package...)
