### ISSUE TITLE
Update gomacro

### ISSUE THREAD

**Issue by fiorix** [gopherdata/gophernotes#132]
gomacro is one of the vendor'ed dependencies of gophernotes. I'd like to update it to get https://github.com/cosmos72/gomacro/pull/33 in gophernotes.

Tested locally, works as expected.

**Comment by cosmos72** [comment]
I happen to know :)

For the moment, gophernotes uses gomacro `stable` branch not to pull in (experimental) generics - but that's not a problem, as I backported the same fix also to gomacro `stable`

**Comment by fiorix** [comment]
Ah. You're ahead of me. I didn't even realize :)

I guess you can drop my pull request then. Can you release a new tag v1.0.0-RC2 or something?

**Comment by cosmos72** [comment]
Thanks for reminding :)

Yes, it's time for a new release - there are already a lot of changes and improvements since the last one.

I am a bit busy RL, but I should manage in the next days.

**Comment by QuLogic** [comment]
Any time for a new tag perhaps?
