### ISSUE TITLE
variadic parameter must be of unnamed slice type

### ISSUE THREAD

**Issue by hlalibe** [gopherdata/gophernotes#135]
Struggling with the following code (which i simplified),
Error is on line: `book_up_data = append(book_up_data, stringup)`
If i comment it out, works ok.
Error message is: t`ypes.NewSignature: variadic parameter must be of unnamed slice type`

```
//create empty slice for up data
var book_up_data plotter.Values

//read 60 rows of up data and append together in slice
j := 1
for j <= 60 {
    stringup, err := strconv.ParseFloat(df[i+j-1][16], 64)
    if err != nil {
        panic(err)
    }
    book_up_data = append(book_up_data, stringup)

    //move to next row
    j = j + 1
}
```
I've researched the topic of variadic parameters and unnamed slice type and tried to change the definition of book_up_data, but no results. The overall code is meant to prepare data to produce a chart. df is created by reading the content of an excel file, works nicely. No error messages when running program from terminal.

**Comment by sbinet** [comment]
does it work if you replace it with:
```go
book_up_data = append(book_up_data, plotter.Value{stringup}...)
```

**Comment by hlalibe** [comment]
I then get for that same line:
`repl.go:11:41: not a type: plotter.Value <*ast.SelectorExpr>`

**Comment by SpencerPark** [comment]
I think this is a gomacro bug so I'll bring @cosmos72 into the discussion here.

Using a type around a slice with variadic signatures is not allowed by `types`.  See [types.NewSignature](https://golang.org/src/go/types/type.go?s=5598:5676#L201). 

The following doesn't work:

```go
type T []float64
var t T
append(t, 1.0)
```

where as this does

```diff
type T []float64
- var t T
+ var t []float64
append(t, 1.0)
```

**Comment by cosmos72** [comment]
Thanks for the extremely short code showing the problem, it made fixing it much faster :)

**Comment by hlalibe** [comment]
thanks @cosmos72 , it's working fine on my side now.
