### ISSUE TITLE
Vendoring of gomacro makes gophernotes complain about gomacro location

### ISSUE THREAD

**Issue by kortschak** [gopherdata/gophernotes#136]
Currently the README says that the success of gophernotes installation can be checked with `gophernotes` and shows a clear reason for a run failure. Now gophernotes vendors gomacro; this means that [gomacro is not necessarily in the location that gomacro will look for itself](https://github.com/gopherdata/gophernotes/blob/053926923734fb2deb8a533b7b469c83d0641d53/vendor/github.com/cosmos72/gomacro/base/util.go#L140).

I guess this means that either the vendored copy needs to be modified, or gomacro needs to get smarter about the possibility that it has been vendored.

/cc @cosmos72

**Comment by gedw99** [comment]
Try runpkg golang package.

It gets around this specific problem well if I understand the issue
correctly.
