### ISSUE TITLE
Odd Interaction between standard packages and some third party packages

### ISSUE THREAD

**Issue by vsivsi** [gopherdata/gophernotes#151]
Hi, We just started noticing errors related to the use of the standard `runtime.NumCPU()` package/method after adding a third party import (that otherwise works fine).

Reproduction:

```golang
package main

import (
   "runtime"

   // "gonum.org/v1/plot/plotter"
)

func main () int {
   return runtime.NumCPU()
}

main()   // Returns 20 on my machine
```

If you uncomment the "gonum" import and re-run, then we get this error when executing the definition of `func main`:

> inconsistent function type: func() int has 1 params - including receiver type interface{Len() int; XError(int) (float64, float64); XY(int) (float64, float64)}
      but its reflect.Type: func() int has 0 params

Once it is in this state, removing the `gonum` import is not sufficient to reverse the error. The gophernotes kernel needs to be restarted for that to work again.

This bevhavior is new. On my machine, it manifested after upgrading to golang 1.11.2 and rebuilding/reinstalling gophernotes.

**Comment by vsivsi** [comment]
BTW, Declaring `main` above is not required to reproduce.  Simply invoking `runtime.NumCPU()` on its own is sufficient.

**Comment by vsivsi** [comment]
I see the same issue if I import "math/rand" and use `rand.Int()` instead of `runtime.NumCPU()`. So this doesn't seem to be related to the `runtime` package specifically.

**Comment by cosmos72** [comment]
Confirmed. Definitely a weird bug, thanks for spotting this!

The same happens with `runtime.NumGoroutine()` and  with any other function whose type is `func () int`, as for example:
```
gomacro> func one() int { return 1 }
gomacro> one()
1       // int
gomacro> import "gonum.org/v1/plot/plotter"
// debug: created file "/home/max/go/src/gomacro_imports/gonum.org/v1/plot/plotter/plotter.go"...
// debug: compiling "/home/max/go/src/gomacro_imports/gonum.org/v1/plot/plotter/plotter.go" ...
gomacro> one()
inconsistent function type: func() int has 1 params - including receiver type interface{Len() int; XY(int) (float64, float64); YError(int) (float64, float64)}
      but its reflect.Type: func() int has 0 params
```

**Comment by cosmos72** [comment]
Update: a minimal example reproducing the problem is: create a file $HOME/go/src/github.com/cosmos72/experiments/main.go containing
```
package experiments

func NewYErrorBars() interface {Len() int} {
	return nil
}
```
then run `go install github.com/cosmos72/experiments` and finally type at gomacro prompt:
```
gomacro> func one() int { return 1 }
gomacro> one()
1       // int
gomacro> import "github.com/cosmos72/gomacro/experiments"
// debug: created file "/home/max/go/src/gomacro_imports/github.com/cosmos72/gomacro/experiments/experiments.go"...
// debug: compiling "/home/max/go/src/gomacro_imports/github.com/cosmos72/gomacro/experiments/experiments.go" ...
gomacro> one()
inconsistent function type: func() int has 1 params - including receiver type interface{Len() int}
      but its reflect.Type: func() int has 0 params
```

**Comment by vsivsi** [comment]
Thanks for confirming the issue and looking into this!
