### ISSUE TITLE
# runtime/cgo exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by trinadhdf** [gopherdata/gophernotes#156]
the error has been occured in window 10 home edition

after executeing the below command

REM Download w/o building.
go get -d -u github.com/gopherdata/gophernotes
cd %GOPATH%\src\github.com\gopherdata\gophernotes\zmq-win

REM Build x64 version.
build.bat amd64

after this the above error is displayed

**Comment by cosmos72** [comment]
Hi,

you also need the 'gcc' C compiler from to build gophernotes. The README.md gives the following instructions to install it on Windows:

Make sure you have the MinGW toolchain:

    [MinGW-w64](https://sourceforge.net/projects/mingw-w64/), for 32 and 64 bit Windows
    [MinGW Distro](https://nuwen.net/mingw.html) for 64 bit Windows only

If you already installed it, make sure 'gcc' is in your %PATH%

**Comment by trinadhdf** [comment]
there is no gcc in the mingw directory

**Comment by cosmos72** [comment]
That's really strange, the purpose of MinGW is to provide the GNU C and C++ compilers 'gcc.exe' and 'g++.exe' on Windows, together with tools needed for C/C++ development (linker, debugger...)

**Comment by cosmos72** [comment]
It's a long time since I last used MinGW...I hope you followed http://mingw.org/wiki/Getting_Started carefully

**Comment by trinadhdf** [comment]
can i get the clarity of %PATH%  mean

**Comment by cosmos72** [comment]
If your question is "what is %PATH% ?" then I can only point you to
https://en.wikipedia.org/wiki/PATH_(variable)
hopefully there is also an accurate translation in your native language

**Comment by trinadhdf** [comment]
ok then should i install these

Make sure you have the MinGW toolchain:

MinGW-w64, for 32 and 64 bit Windows
MinGW Distro for 64 bit Windows only

in path or in os directory

**Comment by cosmos72** [comment]
No, you cannot install MinGW-w64 or MinGW in Windows path:
they are usually installed in `C:\MinGW`, then you need to update the environment variable `%PATH%`  as described in http://mingw.org/wiki/Getting_Started

**Comment by trinadhdf** [comment]
can you have an remote connection and help

**Comment by nbxtruong** [comment]
This one's for you @tkalangi 
http://tdm-gcc.tdragon.net/download

**Comment by amanmd672** [comment]
@nbxtruong hey! I installed that tdm-gcc but I am still getting the same error.
