### ISSUE TITLE
cmd command gophernotes:Command not found

### ISSUE THREAD

**Issue by dapper-hacker** [gopherdata/gophernotes#160]
Hi, I am trying to setup Gophernotes with the jupyter notebook (installed via Anaconda install)
OS - Mac OS Mojave
Go - Go 1.12 (brew install)
Prereqs - brew install (pkg-config and zmq)
$GOPATH - /usr/local/Cellar/go/1.12/bin

I have installed go and then have been trying to install gophernotes. But after successful install of gophernotes when I try to run
$gophernotes
Error: command not found

I think my installation has not compiled and created the gophernotes binary. 
  
<img width="657" alt="image" src="https://user-images.githubusercontent.com/7928115/53779031-9caa8600-3eb3-11e9-8281-f374041de928.png">
<img width="737" alt="image" src="https://user-images.githubusercontent.com/7928115/53779096-cd8abb00-3eb3-11e9-8e93-efc102374bcf.png">

**Comment by dapper-hacker** [comment]
I had to run 
go build 
from the src folder to build the binary. Its unexpected or intended?

**Comment by sbinet** [comment]
as per the instructions for Mac:

- https://github.com/gopherdata/gophernotes#mac

that's expected. (`go get` retrieves the sources, its dependencies, compiles everything and installs the binary under `$GOPATH/bin`. `go build` just builds and puts the resulting binary in the current directory by default.)
