### ISSUE TITLE
zmq4 error

### ISSUE THREAD

**Issue by mogarg** [gopherdata/gophernotes#164]
OS: macOS Mojave 10.14.3

I am getting the following error. Basically, the kernel does not start and throws the following error.

```
jupyter notebook
[I 00:50:41.717 NotebookApp] Serving notebooks from local directory: /Users/mogarg
[I 00:50:41.717 NotebookApp] The Jupyter Notebook is running at:
[I 00:50:41.717 NotebookApp] http://localhost:8888/?token=0318e32ac2508446dd390d9397f8f18fb15361126b61021f
[I 00:50:41.718 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:50:41.722 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///Users/mogarg/Library/Jupyter/runtime/nbserver-21124-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=0318e32ac2508446dd390d9397f8f18fb15361126b61021f
[I 00:50:51.319 NotebookApp] Kernel started: a6685d9b-bdaa-4076-9b23-fbbdcc7afaa6
2019/03/18 00:50:51 zmq4 was installed with ZeroMQ version 4.2.2, but the application links with version 4.3.1
[I 00:50:54.320 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
2019/03/18 00:50:54 zmq4 was installed with ZeroMQ version 4.2.2, but the application links with version 4.3.1
[I 00:50:57.337 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
2019/03/18 00:50:57 zmq4 was installed with ZeroMQ version 4.2.2, but the application links with version 4.3.1
[I 00:51:00.348 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
2019/03/18 00:51:00 zmq4 was installed with ZeroMQ version 4.2.2, but the application links with version 4.3.1
[I 00:51:03.364 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
2019/03/18 00:51:03 zmq4 was installed with ZeroMQ version 4.2.2, but the application links with version 4.3.1
[W 00:51:06.383 NotebookApp] KernelRestarter: restart failed
[W 00:51:06.383 NotebookApp] Kernel a6685d9b-bdaa-4076-9b23-fbbdcc7afaa6 died, removing from map.
^C[I 00:51:09.140 NotebookApp] interrupted
```

Tried to debug using,

```
brew info zmq
zeromq: stable 4.3.1 (bottled), HEAD
```

**Comment by vsivsi** [comment]
@mogarg  Did you find a solution to this issue? I'm seeing the same thing and hope to avoid duplicating effort.

**Comment by vsivsi** [comment]
For future users: it looks like in my case, `brew` upgraded my zeromq libraries from v4.2.4 to v4.3.1, and so I needed to update and rebuild (or remove and completely reinstall) gophernotes so that it was linked against the same version at runtime that is was originally built against.

**Comment by Naohiro2g** [comment]
In my case, zmq4.3.3 was installed and got the error "zmq4 was installed with ZeroMQ version 4.3.2, but the application links with version 4.3.3"

How to install zeromq 4.3.2: 
Search commit hash of 4.3.2 in the log then checkout.

cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/
git checkout 915a80b94801fc6339bbd8fb802e7ee347913145 zeromq.rb
brew unlink zeromq
brew install zeromq
git reset --hard
brew link zeromq

**Comment by sbinet** [comment]
Nowadays gophernotes is using a pure-Go zmq4 library so that kind of error is most probably coming from an installation problem of jupyter itself rather than gophernotes.

**Comment by sbinet** [comment]
Closing as 'not a gophernotes issue anymore'.

(Feel free to reopen if you think that's not the case)
