### ISSUE TITLE
[ABOUT BUILD]  go mod  may effect the kernel/kernel.json place

### ISSUE THREAD

**Issue by yutiansut** [gopherdata/gophernotes#183]
@sbinet 

the kernel.json used to be inplaced in  /go/src/

which in [Dockerfile](https://github.com/gopherdata/gophernotes/blob/master/Dockerfile#L40)

```
    && mkdir -p ~/.local/share/jupyter/kernels/gophernotes \
    && cp -r /go/src/github.com/gopherdata/gophernotes/kernel/* ~/.local/share/jupyter/kernels/gophernotes \
    ## clean

```

while in 0.5 version, gophernotes been installed as a go mod, while actually the kernel.json in
```
/root/go/pkg/mod/github.com/gopherdata/gophernotes@v0.5.0/kernel
```
so maybe affected by this change

maybe change this to 

```
RUN cd ~/.local/share/jupyter/kernels/gophernotes \
  && wget https://raw.githubusercontent.com/gopherdata/gophernotes/master/kernel/kernel.json \
  && wget https://raw.githubusercontent.com/gopherdata/gophernotes/master/kernel/logo-32x32.png \
 && https://raw.githubusercontent.com/gopherdata/gophernotes/master/kernel/logo-64x64.png 
```

would be better

**Comment by sbinet** [comment]
there's this line in [Dockerfile](https://github.com/gopherdata/gophernotes/blob/v0.5.0/Dockerfile#L5):
```
ADD . /go/src/github.com/gopherdata/gophernotes/
```

so line 40 is expected to be fine whatever the "build mode" of Go.

**Comment by yutiansut** [comment]
opts~  thanks~

**Comment by yutiansut** [comment]
![image](https://user-images.githubusercontent.com/11537812/65964358-65bf4180-e48f-11e9-838f-a111e156edbe.png)
finnally ok~  thanks for your help again~~

**Comment by cosmos72** [comment]
Update: I am working on Go 1.11 modules support for both gomacro and gophernotes:

https://github.com/gopherdata/gophernotes/pull/189 also contains module-related fixes to Dockerfile and Dockerfile.DS

**Comment by cosmos72** [comment]
Should be fixed now that https://github.com/gopherdata/gophernotes/pull/189 is merged
