### ISSUE TITLE
print statement outputs integer + <nil>

### ISSUE THREAD

**Issue by RafalSkolasinski** [gopherdata/gophernotes#191]
Hey everyone,

First of all, huge thanks for creating this project. For someone moving from Python to Go this is the first thing I hoped to find!

However, I noticed a small issue when running `gophernotes` from your docker image `gopherdata/gophernotes:latest-ds`.  Simple `fmt.Println(a)` behave differently than in visualisation in your readme, see screenshot:

![image](https://user-images.githubusercontent.com/10928117/70853005-2a35f000-1ea0-11ea-9b4c-dd9b19c1fbac.png)

**Comment by cosmos72** [comment]
The animation in README.md is old and no longer fully accurate.
This behavior is actually intentional - see #179 for a description of the reasons behind it.
