### ISSUE TITLE
Can not work with go-chart

### ISSUE THREAD

**Issue by naiba** [gopherdata/gophernotes#197]
```
import (
    "bytes"
    "github.com/wcharczuk/go-chart" //exposes "chart"
)

graph := chart.Chart{
    Series: []chart.Series{
        chart.ContinuousSeries{
            XValues: []float64{1.0, 2.0, 3.0, 4.0},
            YValues: []float64{1.0, 2.0, 3.0, 4.0},
        },
    },
}

buffer := bytes.NewBuffer([]byte{})
graph.Render(chart.PNG, buffer)
display.PNG(buffer.Bytes())
```

**Comment by naiba** [comment]
The error is: `reflect: Call using *chart.Chart as type chart.Chart`

**Comment by naiba** [comment]
Any body here?

**Comment by cosmos72** [comment]
I cannot reproduce the problem - it works for me, see attached screenshot
![gophernotes_issue_197](https://user-images.githubusercontent.com/1947270/74963181-96d5e980-5411-11ea-90b1-01341c48293e.png)

Which version of Go compiler and gophernotes are you using, and on what OS?

**Comment by naiba** [comment]
@cosmos72 Thanks for your replay, I use docker.
```
docker run -it -p 8888:8888 gopherdata/gophernotes:latest-ds
```
