### ISSUE TITLE
chmod +w ./kernel.json required for mac installation

### ISSUE THREAD

**Issue by raphaelreis** [gopherdata/gophernotes#200]
First time I open an issue so not sure it is the good place to write this note...

While installing the kernel for jupyter, I ran the command:

`sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json`

and got this error: 

`zsh: permission denied: kernel.json`

I tried to use the sudo command but the error remained.

I solved the issue using: 

`chmod +w ./kernel.json`

Apperently my computer has not burn yet so it must not be a mistake to proceed like this.

**Comment by cosmos72** [comment]
Thanks, I will update the installation instructions.

You must have had a file `kernel.json` from a previous installation, marked read-only - the same will happen to everybody upgrading from an older version of gophernotes.
