### ISSUE TITLE
warning: could not find package "github.com/gopherdata/gophernotes/imports" in $GOPATH

### ISSUE THREAD

**Issue by genert** [gopherdata/gophernotes#206]
I am getting this warning in notebooks, where I import some third-party libraries.

For example, if I include following imports in notebook:

```go
import (
    "fmt"
    
    "github.com/gonum/stat"
    "github.com/gonum/stat/distuv"
)
```

The warning appears.

<img width="936" alt="Screenshot 2020-04-28 at 21 51 45" src="https://user-images.githubusercontent.com/1218788/80525796-78a0e280-899a-11ea-9cb6-1fa24d0e1f0f.png">

Golang version:
```
(base) ➜  ai-notebooks git:(master) go version
go version go1.14.1 darwin/amd64
```

MacOS version:
```
(base) ➜  ai-notebooks git:(master) sw_vers -productVersion
10.15.4
```

Gopath:
```
(base) ➜  ai-notebooks git:(master) echo $GOPATH
/Users/genertorg/go
```

Gophernotes bin:
```
(base) ➜  ai-notebooks git:(master) "$(go env GOPATH)"/bin/gophernotes
2020/04/28 21:50:47 Need a command line argument specifying the connection file.
```

**Comment by sbinet** [comment]
unrelated to your issue but these imports:
```go
"github.com/gonum/stat"
"github.com/gonum/stat/distuv"
```
are deprecated.

please use `gonum.org/v1/gonum/stat` and `gonum.org/v1/gonum/stat/distuv`.

**Comment by cosmos72** [comment]
it's a harmless warning. I could even hide it...
It tells you that since gophernotes sources are not inside $GOPATH,
injecting imports inside gophernotes sources will not work

**Comment by RafalSkolasinski** [comment]
> it's a harmless warning. I could even hide it...

Please do :-). Package that I wanted to load was taking some time to load and this error scarred me that things are not working :D

**Comment by cosmos72** [comment]
Warning removed.
