### ISSUE TITLE
Unable to run notebook with error: packages.Load() could not find package

### ISSUE THREAD

**Issue by kortschak** [gopherdata/gophernotes#216]
Gophernotes looks like it's failing again for me. Attempting to run the notebook at https://mybinder.org/v2/gh/kortschak/graphprac/master?filepath=graph-prac.ipynb gives the following (Go1.13).

```
error loading package "github.com/kortschak/graphprac" metadata: packages.Load() could not find package "github.com/kortschak/graphprac"
```

I get this error when running locally (Go1.15).

```
error loading package "github.com/kortschak/graphprac" metadata: -: cannot find module providing package github.com/kortschak/graphprac: working directory is not part of a module
```

I don't know if this is related to #184, but the local error suggests so.

**Comment by kortschak** [comment]
I have just reinstalled gophernotes locally with version v0.7.1 and it is working locally, so this issue becomes a question about what it is that I'm doing wrong in the [postBuild](https://github.com/kortschak/graphprac/blob/master/postBuild) on the MyBinder configuration. I'll have a little play to see if I can fix that.

**Comment by kortschak** [comment]
Resolved with some care given to the postBuild.

**Comment by cosmos72** [comment]
Good to hear that you solved this problem.

Would you care to post the differences between the 'broken' and the 'working' build script ?

Or maybe the critical parts were the following?
```
export GO111MODULE=on
# ...
go get github.com/gopherdata/gophernotes@v0.7.1
```

**Comment by kortschak** [comment]
The change that fixed the problem was [this](https://github.com/kortschak/graphprac/commit/072e6465476ea1f1e78fe0d0803a85630748397e). Within that mess, I'd say the crucial lines are ones that you mentioned and then copying and replacing the kernel.json to include the $GOROOT and updated $PATH that otherwise lacks the go tool.
