### ISSUE TITLE
error loading package "github.com/parnurzeal/gorequest" metadata: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

### ISSUE THREAD

**Issue by ilaer** [gopherdata/gophernotes#221]
![image](https://user-images.githubusercontent.com/5914968/100822792-f297cd80-348d-11eb-8086-8f2c19e7d82f.png)

**Comment by cosmos72** [comment]
Hello @ilaer
importing third-party packages (i.e. outside the Go standard library) currently only works on Linux and Mac OS x,
and - what's probably missing in your case - requires the Go compiler to be installed and added to $PATH
