### ISSUE TITLE
Inconsistent behavior w/ reflect.TypeOf

### ISSUE THREAD

**Issue by icncsx** [gopherdata/gophernotes#225]
```go
type T string

t := T("what")
tt := reflect.TypeOf(t)
fmt.Println(tt) // prints string, should be main.T
```

**Comment by cosmos72** [comment]
This is a known limitation:
Go standard library does not provide any way to create new named types at runtime - only new unnamed types can be created.

Thus it's currently not possible to fix this issue.

There is an open enhancement proposal https://github.com/golang/go/issues/39717 to add such feature - I started implementing it some months ago, but it's still unfinished
