### ISSUE TITLE
support for go 1.17?

### ISSUE THREAD

**Issue by encryptblockr** [gopherdata/gophernotes#235]
Current docker image is using go 1.11.4 but current stable version of go is 1.17
Is there a path to maybe modifying Dockerfile to build image to use go 1.17?
Please let me/us know if this is possible and any list of steps to guide to solution

Thanks

```
/ # go version
go version go1.11.4 linux/amd64

/ # go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build558705597=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by cosmos72** [comment]
The `Dockerfile.*` probably needs to be updated. @sbinet maybe can help?

**Comment by sbinet** [comment]
sure. I'll wait for a couple of days to give a bit of time for https://github.com/gopherdata/gophernotes/pull/238 to be updated and merged, so as to not duplicate work (nor deter new contributors)

**Comment by sbinet** [comment]
ok, #238 timed out.
see:
- https://github.com/gopherdata/gophernotes/pull/242
