### ISSUE TITLE
Docker image update?

### ISSUE THREAD

**Issue by PhilipLutley** [gopherdata/gophernotes#244]
Just checking if the docker image has been abandoned?
Last update was about 5 years ago.
https://hub.docker.com/r/dwhitena/gophernotes/tags

**Comment by PhilipLutley** [comment]
I should elaborate - the gophernotes image (gopherdata/gophernotes:latest) is running an old version of go which is what prompted me to ask.

/ # go version
go version go1.11.4 linux/amd64

**Comment by sbinet** [comment]
the `Dockerfile*` have been recently updated.
but @dwhitena has the r/w perms on the docker hub.

you should be able to build a rather new and shiny docker image from sources.

**Comment by PhilipLutley** [comment]
> the `Dockerfile*` have been recently updated. but @dwhitena has the r/w perms on the docker hub.
> 
> you should be able to build a rather new and shiny docker image from sources.

ok, will do.

**Comment by LiZeC123** [comment]
@sbinet maybe we can use github action to generate new docker image, if you need, I can create a pull request for this.
