### ISSUE TITLE
extra output?

### ISSUE THREAD

**Issue by PhilipLutley** [gopherdata/gophernotes#247]
This is probably down to my lack of understanding notebooks..

Is there any way I can get rid of the extra output cell? It's giving me my output plus an extra character count cell (I think).

![Screenshot 2022-02-20 172748](https://user-images.githubusercontent.com/18010907/154856088-385acc1b-272c-436e-8e72-08a6fc025980.png)

**Comment by cosmos72** [comment]
The output cell shows the values returned by the last expression - in your case, `fmt.Println(...)`.

This is a general feature, and useful in many cases - see this screenshot for an example 
![image](https://user-images.githubusercontent.com/1947270/155148419-f1b1cb5f-9779-4a60-bf38-f948fe0725de.png)

If you want to suppress the values returned by the last expression, you can assign them to `_` or wrap the expression inside `{ ... }` to convert it to a statement (Go statements do not return values) - for example
![image](https://user-images.githubusercontent.com/1947270/155149053-1c881298-94e2-4c83-aa66-94f7ad58da36.png)
