### ISSUE TITLE
Proposal: present Gophernotes at Golab 2022 (Italy) ?

### ISSUE THREAD

**Issue by cosmos72** [gopherdata/gophernotes#249]
@sbinet @SpencerPark @dwhitena 
Did anyone already present Gophernotes at some conference?

I will attend to [Golab 2022 (Italy, 2-4 october)](https://golab.io/) and I think it could be an interesting topic to present there.

For reference, @sbinet presented [go-hep](https://go-hep.org/) at Golab 2019 , and I presented code generation with gomacro (not gomacro itself) at Golab 2018.

**Comment by sbinet** [comment]
SGTM (I don't recall presenting Gophernotes, or just in passing, in my usual laundry list of science-y projects in Go.)

GoLab is a really nice conference :)

**Comment by cosmos72** [comment]
The deadline for proposal submission is June 12 , and I don't really have the (spare) time to write a proposal for that date - that's why I was asking:

if someone is willing to step up and present gophernotes I think it could really be a mice and interesting topic

**Comment by cosmos72** [comment]
The proposal submission deadline has passed. Closing this.
