### ISSUE TITLE
External repo not working

### ISSUE THREAD

**Issue by 0xstepit** [gopherdata/gophernotes#257]
Hello, I'm trying to use gophernotes to test types of the following repo: https://github.com/cosmos/cosmos-sdk

I import the packages

```
import (
    "fmt"
    sdk "github.com/cosmos/cosmos-sdk/types"
)

```
and try to use:
```

addr := "juno1juczud9nep06t0khghvm643hf9usw45r4v7lq6"
valAddr := sdk.MustAccAddressFromBech32(addr)
```

On the terminal I receive the following message:

`repl.go:2:12: not a type: sdk.MustAccAddressFromBech32 <*ast.SelectorExpr>
`

How can I solve it? thanks

**Comment by yg7001** [comment]
Also I meet this.

**Comment by chenjpu** [comment]
![image](https://github.com/gopherdata/gophernotes/assets/1785778/f5e881de-652d-4393-af4a-65332f242a2a)

**Comment by ammar-elsabe** [comment]
Bumping this, I have the same issue

**Comment by BenoitBotton** [comment]
Has anyone made any progress on this? same issue:
![image](https://github.com/gopherdata/gophernotes/assets/10010115/2d6c752f-608e-4cc7-a82a-2c3eb4de1b78)

**Comment by cosmos72** [comment]
That's really strange: importing packages from the standard library is supposed to *always* work, and in case it fails, it's unrelated to this issue

**Comment by cosmos72** [comment]
Commit 55142043d19696ba037e3e93f9ec6c7f8436e82d fixes most issues importing packages.

Some imports may still fail. Known reasons are:

* package being imported is or depends on a package that conflicts with gophernotes dependencies.
Example: `import "github.com/cosmos/cosmos-sdk/types"` currently fails with:
```
error loading plugin "[...]/import_1.so": plugin.Open("[...]/import_1"): 
  plugin was built with a different version of package golang.org/x/text/transform
```
* on Windows, importing third-party packages is supported only inside WSL, which is itself quite untested.
   In alternative, you can use gophernotes inside Docker or inside a Linux VM.
