### ISSUE TITLE
compile: version "go1.19.4" does not match go tool version "go1.20.2" # unicode/utf16

### ISSUE THREAD

**Issue by Kingson4Wu** [gopherdata/gophernotes#259]
when execute `go install`:
compile: version "go1.19.4" does not match go tool version "go1.20.2" # unicode/utf16

my local go version:
 go version
go version go1.20.2 darwin/amd64

**Comment by cosmos72** [comment]
Hi @Kingson4Wu,
this is quite an unexpected error.

Is it possible that by mistake you installed go 1.20.2 **on top of** go 1.19.4, without first removing the latter?

**Comment by Kingson4Wu** [comment]
> Hi @Kingson4Wu, this is quite an unexpected error.
> 
> Is it possible that by mistake you installed go 1.20.2 **on top of** go 1.19.4, without first removing the latter?

yes, you are right!
