### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by Arundas666** [gopherdata/gophernotes#264]
package main

import (
	"fmt"
)

func fibonacci(n int, c chan int) {
	x, y := 0, 1
	for i := 0; i < n; i++ {
		c <- x
		x, y = y, x+y
	}
	close(c)
}

func main() {
	c := make(chan int, 10)
	go fibonacci(cap(c), c)
	for i := range c {
		fmt.Println(i)
	}
},
This is not working in gophernotes, can anyone explain why?

**Comment by cosmos72** [comment]
Hi @Arundas666,

I tried to reproduce your issue, but it works as expected for me.
Note: `main()` is not special in gophernotes, so it must be called explicitly.

![image](https://github.com/gopherdata/gophernotes/assets/1947270/89b429b6-5d3c-4ec3-88a3-1756aede2c08)
