### ISSUE TITLE
Failed to run if/else in Docker

### ISSUE THREAD

**Issue by gangtao** [gopherdata/gophernotes#54]
When I run a simple if/else statement in a docker like this:
`if 7%2 == 0 {`
`fmt.Println("7 is even")`
`} else {`
`fmt.Println("7 is odd")`
`}`

it failed to run and the server log output is:
`Error running goimports:`
`/tmp/002613501/func_proxy.go:4:4: expected declaration, found 'if'`

regarding a for loop, it works for a single line code like this "for i:= 1; i < 5; i++ {fmt.Println("Line %s", i)}"
but not work if format the code like this:
`for i:= 1; i < 5; i++ {` 
`fmt.Println("Line %s", i)` 
`}` 

what is the limitation here?

**Comment by dwhitena** [comment]
Thanks @gangtao.  Great catch.  I will work on fixing this, which seems to be a bug.

**Comment by dwhitena** [comment]
This likely has to do with how I'm parsing braces `{` and `}`

**Comment by gangtao** [comment]
@dwhitena great to hear it, looking forward to using the fixed version soon.

**Comment by dwhitena** [comment]
@gangtao Sorry it has taken so long, but this should be fixed in the v1 RC.  Closing for now, but please reach out with any issues.  Thanks!
