### ISSUE TITLE
Failed to define a function in Docker

### ISSUE THREAD

**Issue by teramonagi** [gopherdata/gophernotes#55]
When I wrote the code like the following In a note book
```go
import "fmt"
hoge := func () int {
    return 1
}
fmt.Println(hoge())
```
It works well.

On the other hand, if I try to define a function like this
```go
func moge() int {
    return 1
}
fmt.Println(moge())
```
It showed the error.
```
/tmp/361320456/func_proxy.go:8:1: expected declaration, found 'IDENT' fmt
```

Is that the correct behavior which is supposed?

**Comment by dwhitena** [comment]
Interesting.  Thanks for sharing this behavior @teramonagi.  This is not expected, or at least shouldn't be expected.  There is a little weirdness lingering in the parsing of function braces I think.  I will look into this along with https://github.com/gopherds/gophernotes/issues/54, which both are stemming from some kind of brace parsing weirdness.  Hopefully will fix both of these in the next release.

**Comment by bregydoc** [comment]
Hi, I have a similar problem when I want declare a function in a cell but call it in other cell. The result this is:
![image](https://cloud.githubusercontent.com/assets/18302365/22252112/2a57b18c-e21b-11e6-8836-f4273793caa7.png)

**Comment by dwhitena** [comment]
Thanks for the other example @bregydoc.  I've been slammed lately, but I'm traveling to a few conferences soon, and hoping to get this fixed very soon.

**Comment by buyology** [comment]
Any update on this?

**Comment by dwhitena** [comment]
@buyology @bregydoc and @teramonagi.  Sorry it took so long to resolve this.  We just did a major refactor of gophernotes, and I think these issues are fixed.  Closing for now, but please reach out if there are lingering issues.
