### ISSUE TITLE
Worker Pools Example is broken

### ISSUE THREAD

**Issue by JustinJudd** [gopherdata/gophernotes#58]
The Worker Function of the worker pools example does not work, with the following error:
`func literal evaluated but not used`

Testing, I seem to get this error for any function of the form
```go
func name() {

}
```

functions that use the following form work, but are limiting, because you wouldn't be able to compose functions onto structs to satisfy interfaces.
```go 
name := func() {

}
```

**Comment by dwhitena** [comment]
@JustinJudd Thank you for reporting this and sorry for the extreme delay in responding.  This should work in the new v1 RC.  Please let me know if it does not.  Closing for now.
