### ISSUE TITLE
"import as" not take effect

### ISSUE THREAD

**Issue by clouds56** [gopherdata/gophernotes#59]
run this in jupyter notebook
```
In [1]: import m "math"
In [2]: m.Sin(1)
# command-line-arguments
/var/folders/.../gophernotes_session.go:10: undefined: m in m.Sin
```

here's the [spec](https://golang.org/ref/spec#Import_declarations)

**Comment by dwhitena** [comment]
Sorry for the delay here.  Yes, this is not supported quite yet, but hoping to get around to it soon.

**Comment by dwhitena** [comment]
@clouds56, we have done a major refactor on gophernotes and replaced the interpreter with `gomacro`.  Unfortunately gomacro doesn't support these named imports for now.  Hopefully we could merge something upstream at some point.

**Comment by cosmos72** [comment]
Gophernotes has recently updated its vendored copy of gomacro, and now it works.

See the attached screenshot
![screenshot_20180405_143348](https://user-images.githubusercontent.com/1947270/38366017-bc93d272-38de-11e8-8031-afb55111ffda.png), that shows the output of:
```
import f "fmt"
f.Println("hello")
```

**Comment by cosmos72** [comment]
Gophernotes has recently updated its vendored copy of gomacro, and now it works.

See the screenshot below, that shows the output of:
```
import m "math"
m.Sin(1)
```
![screenshot_20180405_144321](https://user-images.githubusercontent.com/1947270/38366374-c773d10a-38df-11e8-9bcc-f0fd3fb62a5a.png)

**Comment by dwhitena** [comment]
Awesome, thanks for the update here @cosmos72!
