### ISSUE TITLE
no Out[n] statements created from jupyter notebook

### ISSUE THREAD

**Issue by aleks-mariusz** [gopherdata/gophernotes#61]
I downloaded the docker image and tried to follow along with a Hello World application (as i was having similar issues trying to just get it working via a miniconda installer (aka mini version of anaconda, python 3).  

Jupyter works, starts up properly, but when i enter in the exact same thing as the README has for the hello world app, i don't see any Out's (except for the Sprintf() call).

See attached screen shot, i'm starting it as per the README:

```
$ docker run -p 18888:8888 -d dwhitena/gophernotes jupyter notebook --no-browser --ip=0.0.0.0
504f0499e5a8f57b202ddf06052fba45fe4cc2b3c10543315f4b395be33fe81c
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                     NAMES
504f0499e5a8        dwhitena/gophernotes   "jupyter notebook ..."   9 minutes ago       Up 8 minutes        0.0.0.0:18888->8888/tcp   adoring_boyd
$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
dwhitena/gophernotes   latest              4cf782ddc225        6 months ago        979 MB
```

![screen shot 2017-04-27 at 21 11 59](https://cloud.githubusercontent.com/assets/2719694/25502396/5070a100-2b8e-11e7-96b7-1a103b27ad8b.png)

**Comment by aleks-mariusz** [comment]
hello? Is there something i'm just doing wrong? would really like to use this with jupyter but simply not being shown the evals Outs (unless explicitly using a function sending data to stdout like fmt.Printf()  

would be nice to not have to pepper all my exploratory code with these funcs just to work around this..

**Comment by aleks-mariusz** [comment]
As this project appears to be abandoned, i found an alternative.. gophernotes.. it seems to be an actually (more actively) maintained fork of this

https://github.com/fabian-z/gopherlab

I tested my same setup (giving up on the broken docker image) and it works as expected and prints Out[n] for every line (even teh import which i think is weird but better extra output than missing output)

**Comment by dwhitena** [comment]
Hi @aleks-mariusz.  I apologize for the very late reply here.  I have been traveling quite a bit lately, but hoping to knock some of these out soon.  

I'm glad you found gopherlab, and hope to collaborate with them soon.  I need a couple weekends to clean out this project, sync up with them, and get some momentum.

**Comment by dwhitena** [comment]
Note also, part of the reason that I am waiting on some of this dev is that a wayyyyy more robust interpreter is coming soon as part of the go-interpreter project: https://github.com/go-interpreter/wagon.  They are building this such that it should plug and play with gophernotes.  

That being said, no excuse for not being more active on pressing issues here.  Hope to address this soon.

**Comment by aleks-mariusz** [comment]
Ahh thanks for the response, appreciate you getting back to me.  Will keep an eye out on that other project as well!

**Comment by dwhitena** [comment]
@aleks-mariusz This should be fixed v1 (RC just released).  Can you confirm?

**Comment by dwhitena** [comment]
Closing this, as it is now fixed in v1-RC. Let me know if you see other weirdness though.
