### ISSUE TITLE
Kernel shows up but does not work

### ISSUE THREAD

**Issue by Mxbonn** [gopherdata/gophernotes#71]
Hello, 
I installed gophernotes following the instructions and now `Go` shows up as an option in my notebooks but when I try to execute something I get errors like 
```
/var/folders/z5/zxdqxy_9595fs4z40wz496x40000gn/T/824132211/func_proxy.go:4:4: expected declaration, found 'IDENT' ...
```
![image](https://user-images.githubusercontent.com/11473168/29776221-4538b07c-8c08-11e7-807f-3bfd45e06904.png)

I'm working with OS X El Capitan (10.11.6) and Go 1.9 (Issue was also present on 1.8)

**Comment by sbinet** [comment]
not sure whether that is the underlying issue, but...
does it work if you type:

```go
hello := "hello"
```

(ie: double-quotes, not single-quotes)

**Comment by Mxbonn** [comment]
Uch I feel so stupid.. :p yes that worked.
