### ISSUE TITLE
about zmq

### ISSUE THREAD

**Issue by hsz1273327** [gopherdata/gophernotes#8]
I have zmq4 in my mac, and I did try to install gophernotes. but there is a error:
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP 

so i installed zmq2.2 by homebrew. how can i Iinstall gophernotes with  zmq2.2 ?

**Comment by dwhitena** [comment]
What happens when you try to re-install gophernotes after installing zmq2.2:

```
go get github.com/gophergala2016/gophernotes
```

Also, see this closed issues for related comments: https://github.com/gophergala2016/gophernotes/issues/4

**Comment by P1xt** [comment]
Installed gophernotes to my mac today (el-capitan using homebrew exactly per instructions on README):

Received the following error when I got to the "go get github.com/gophergala2016/gophernotes" part:

pkg-config --cflags libzmq libzmq libzmq libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found

The following from the command line fixes this issue:
export PKG_CONFIG_PATH=/usr/local/Cellar/zeromq22/2.2.0/lib/pkgconfig/

**Comment by dwhitena** [comment]
@P1xt Thanks for the info.  I added a note to the README.

**Comment by dwhitena** [comment]
This info is updated in the README.  Going to close this issue.

**Comment by fvisconti** [comment]
Hi there, still have problems:
```
francesco@sherlock:~$ go get -u -v github.com/gopherdata/gophernotes...
github.com/gopherdata/gophernotes (download)
github.com/gopherdata/gophernotes/vendor/github.com/pebbe/zmq4
# pkg-config --cflags libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
pkg-config: exit status 1
francesco@sherlock:~$ export PKG_CONFIG_PATH=/home/francesco/miniconda3/envs/ml/lib/pkgconfig/libzmq.pc
francesco@sherlock:~$ go get -u -v github.com/gopherdata/gophernotes...
github.com/gopherdata/gophernotes (download)
github.com/gopherdata/gophernotes/vendor/github.com/pebbe/zmq4
# pkg-config --cflags libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
pkg-config: exit status 1
francesco@sherlock:~$ echo $PKG_CONFIG_PATH 
/home/francesco/miniconda3/envs/ml/lib/pkgconfig/libzmq.pc

```

**Comment by cosmos72** [comment]
Your system is not finding the libzmq library:
```
# pkg-config --cflags libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
pkg-config: exit status 1
```
this really seems to be a missing requirement rather than a gophernotes issue.

Are you sure you installed ZeroMQ with the [official Mac OS X procedure](http://zeromq.org/intro:get-the-software) ?

**Comment by fvisconti** [comment]
As you can see in my log, I set the `PKG_CONFIG_PATH` variable to a known path, which I found with the `locate` command. 
I'm on Linux, Ubuntu 16.04.

**Comment by cosmos72** [comment]
Sorry, I did not realize your report was for Linux - the original issue was specific to Mac OS X.

The `PKG_CONFIG_PATH` variable should be set to the **directory** containing 'libzmq.pc', not to the file itself. In your case:
```
PKG_CONFIG_PATH=/home/francesco/miniconda3/envs/ml/lib/pkgconfig
export PKG_CONFIG_PATH
```

**Comment by gedw99** [comment]
Mhh why not use NATS? 100% golang message queue.
Can also be embedded in any golang program.

Just a suggestion

**Comment by sbinet** [comment]
@gedw99 because that's the protocol that Jupyter uses.
that said: https://github.com/go-zeromq/zmq4 :)

**Comment by fvisconti** [comment]
Thanks @cosmos72,

when I do 
```
PKG_CONFIG_PATH=/home/francesco/miniconda3/envs/ml/lib/pkgconfig
export PKG_CONFIG_PATH
```
I get
```
# github.com/gopherdata/gophernotes/vendor/github.com/pebbe/zmq4
/usr/bin/ld: warning: libsodium.so.23, needed by /home/francesco/miniconda3/envs/arbitrage/lib/libzmq.so, not found (try using -rpath or -rpath-link)
```
But
```
ll /home/francesco/miniconda3/envs/arbitrage/lib/libzmq.so
lrwxrwxrwx 1 francesco francesco 15 lug 19 12:45 /home/francesco/miniconda3/envs/arbitrage/lib/libzmq.so -> libzmq.so.5.1.5*
```

**Comment by fvisconti** [comment]
I solved this way: 
- install libzmq3-dev via Ubuntu default repo;
- `go get -tags zmq_4_x github.com/gophergala2016/gophernotes`
- set the correct path in `$GOPATH/src/github.com/gopherdata/gophernotes/kernel/kernel.json` to `gophernotes` binary

Cheers
