### ISSUE TITLE
Cannot pull docker images because 'latest' tag does not exist

### ISSUE THREAD

**Issue by ufoscout** [gopherdata/gophernotes#81]
The 'Docker' section of this project main page reports these instructions to run the official images:
```
$ docker run -it -p 8888:8888 gopherdata/gophernotes
$ docker run -it -p 8888:8888 gopherdata/gophernotes-ds
```

However, both the command fail with this issue:
```
$ docker run -it -p 8888:8888 gopherdata/gophernotes
Unable to find image 'gopherdata/gophernotes:latest' locally
docker: Error response from daemon: manifest for gopherdata/gophernotes:latest not found.
See 'docker run --help'.
```

The error is caused by the lack of the 'latest' tag in docker hub. You should solve the tag issue or propose the user to use a tagged version instead of latest:
```
$ docker run -it -p 8888:8888 gopherdata/gophernotes:1.0.0
$ docker run -it -p 8888:8888 gopherdata/gophernotes-ds:1.0.0
```

**Comment by dwhitena** [comment]
This is resolved.  Thanks for bringing it to our attention!
