### ISSUE TITLE
pkg-config: exec: "pkg-config": executable file not found in $PATH

### ISSUE THREAD

**Issue by mogarg** [gopherdata/gophernotes#82]
Mac OSX 10.13

I get this error on running 

`go get github.com/gopherdata/gophernotes`

**Comment by dwhitena** [comment]
I think you just need to do the following:

```
$ brew install pkg-config
```

Let us know if that works, and sorry for the hiccup.

**Comment by mogarg** [comment]
Hey Daniel, 

This worked. I was trying to install gophernotes on a new Macbook. While I had pkg-config installed  in the older mac, it wasn't there in the newer Mac. I would request you to please update your README to reflect this for more unmindful idiots like me. 

Thanks.

**Comment by dwhitena** [comment]
Updated! Thanks so much for bringing this to our attention. I'm sure if you hit this, then other people will as well, so it's super useful.

**Comment by nieroda** [comment]
(this helped) 👍

**Comment by ShubhamRaj16** [comment]
this really helped

**Comment by zhanghuanzhong** [comment]
this helped

**Comment by deadly-poison** [comment]
this helped

**Comment by devenblake** [comment]
Helped for building another repository.

**Comment by kiarash8112** [comment]
this really really helped

**Comment by wyatt-h** [comment]
this helped

**Comment by mashangustc** [comment]
this helped

**Comment by asrivastava-lyft** [comment]
this helped
