### ISSUE TITLE
Where to copy the kernel.json config

### ISSUE THREAD

**Issue by mogarg** [gopherdata/gophernotes#83]
MacOS 10.13 

On checking jupyter --data-dir 
I see that the path is /Library/Jupyter 

I copied the kernel files to this location however when I launch Jupyter the notebook does not show up.

**Comment by dwhitena** [comment]
Hi @mogarg, thanks for the question. What was the exact path to the kernel file.  I think it should be something like:

```
$ mkdir -p ~/Library/Jupyter/kernels/gophernotes
$ cp $GOPATH/src/github.com/gopherdata/gophernotes/kernel/* ~/Library/Jupyter/kernels/gophernotes
```

**Comment by mogarg** [comment]
Got it. It worked. Thanks @dwhitena
