### ISSUE TITLE
Go kernel does not handle multiple returns elegantly/informatively

### ISSUE THREAD

**Issue by kortschak** [gopherdata/gophernotes#85]
In looking into #84 I stumbled on this:

```go
import ("fmt"; "os/user")
fmt.Println(user.Current())
```
    &{0 0 root root /root}
    // warning: expression returned 2 values, using only the first one: [0xc420170730 <nil>]

This appears to be jupyter condensing the pair of returns from `fmt.Println` into a 2-tuple and then complaining about it.

~~Interestingly, the old behaviour of printing returned values when the would be useful has gone, so executing `user.Current()` outputs nothing, where in the past (from memory - I don't have a dwhitena/gophernotes that works here - I will check when I am back at that machine) it would have output the user and nil.~~ I have checked this in an old output and this is obviously a confabulation, though it would be nice that returns are actually printed (as is the case for the python kernel below), particularly if they are going to be complained about.

```python
def foo():
    return 1, 2
foo()
```
    (1, 2)

**Comment by dwhitena** [comment]
Thank you for this info @kortschak. @SpencerPark and I are working through some issues with the multiple returns right now, and I have another issue open for the warning thing (https://github.com/gopherdata/gophernotes/issues/80), which is actually a `gomacro` warning that we need to handle (i.e., these are benign).  I will update here after we work through one or both of those things.

**Comment by dwhitena** [comment]
@kortschak We have merged https://github.com/gopherdata/gophernotes/pull/79, which I think addresses multiple returns in a much better way. Can you confirm that you get useful output now?

**Comment by kortschak** [comment]
That looks very nice to me. Thanks.
