### ISSUE TITLE
Doesn't respond to heartbeat messages

### ISSUE THREAD

**Issue by thomasjm** [gopherdata/gophernotes#89]
Opening this issue per our discussion on e779a2a956d828c37b45081bd92b6ab52b0e88ed. It seems `gophernotes` doesn't quite conform to the Jupyter 5 messaging spec at the moment, because it drops support for the heartbeat thread which echoes back messages on the heartbeat socket.

While this isn't a problem for the common Jupyter frontends (notebook, console, etc.) it is causing a problem for me because I'm working on an alternate frontend that still expects heartbeats to work.

Thanks!

**Comment by SpencerPark** [comment]
I didn't realize the heartbeat was missing until work started on #79 where sleeping on the main thread for any noticeable amount of time disconnected the kernel.

Looking back into your discussion there may have been a better way to implement the heartbeat handler (with that `zmq.Device` forwarding) but nevertheless there is an implementation in 200eb3664494ad42e9648d49b12cb5ae1b980d1c that is not merged yet.

Seeing as this is a separate issue it might be worth pulling the heartbeat changes into a separate PR to get things merged faster as the current one still needs some decisions (unrelated to this) to be made.

**Comment by dwhitena** [comment]
Should be fixed in: https://github.com/gopherdata/gophernotes/pull/79. @thomasjm can you confirm?
