### ISSUE TITLE
Type inference on composite literals

### ISSUE THREAD

**Issue by dyllanwli** [gopherdata/gophernotes#90]
Define a map and the cell returns an error:

```
var p = map[string][]string{"world":{"hello"}}
runtime error: invalid memory address or nil pointer dereference
```

But if I define a empty map and it will not raise a panic.

```
var p = map[string][]string{} // correct.
```

Why this error happened? Could anyone help me to fix that?

**Comment by SpencerPark** [comment]
This is an issue with the underlying interpreter gomacro. The interpreter doesn't have support for the type inference that the go compiler performs on composite literals like this. The solution until that is implemented is to simply include the type when writing the literal:

```go
var p = map[string][]string{"world":[]string{"hello"}}
```

I've opened up an issue cosmos72/gomacro#9 related to this over at gomacro.

**Comment by dwhitena** [comment]
Thanks @SpencerPark!

**Comment by dwhitena** [comment]
I updated the title of this issue to track this on our side.

**Comment by cosmos72** [comment]
fixed in upstream gomacro, see https://github.com/cosmos72/gomacro/issues/9 and https://github.com/cosmos72/gomacro/commit/75e1b439420802d760132f33b30e456e928dbbc6
