### ISSUE TITLE
how can i conver this image for raspberry pi 3?

### ISSUE THREAD

**Issue by baram204** [gopherdata/gophernotes#94]
I want to run it on my pi.

But I got error messages below:
```
~$ docker run -it -d --name gophernotes -e VIRTUAL_HOST=someHostDomain
gopherdata/gophernotes-ds
0bf8557a2ddd3a7d0160993b93f08d1e8b666e5ab57d3b568dbf2026097ad07a
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error".
```

**Comment by cosmos72** [comment]
Raspberry Pi is an ARM system, it cannot run natively a docker image containing amd64 / 386 executables. And amd64 / 386 emulation would be too slow on a Raspberry.

Assuming you have some Linux distribution on your Pi (hopefully Raspbian), you should follow the installation procedure for Linux explained at https://github.com/gopherdata/gophernotes#installation

Start with the prerequisites:
- [go1.9+ for Linux arm](https://dl.google.com/go/go1.10.1.linux-armv6l.tar.gz) Note: remember to add $HOME/go/bin to your $PATH
- [Jupyter notebook for Raspberry Pi](http://www.instructables.com/id/Jupyter-Notebook-on-Raspberry-Pi/)
- [Zeromq and pkg-config for Raspberry Pi](https://github.com/MonsieurV/ZeroMQ-RPi)

Then follow the [gophernotes instructions for Linux](https://github.com/gopherdata/gophernotes#linux) 

Of course, if somebody had prepared a gophernotes docker image for Raspberry Pi, using it would be simpler than the manual procedure listed above. But a quick google search returned nothing relevant.
