### ISSUE TITLE
OS X Installation Error: No package 'libzmq' found

### ISSUE THREAD

**Issue by inancgumus** [gopherdata/gophernotes#96]
```bash
$ go get github.com/gopherdata/gophernotes
# pkg-config --cflags libzmq
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
pkg-config: exit status 1
```

**Comment by rokroskar** [comment]
if you have homebrew, try `brew install zmq`

**Comment by mrchaohe** [comment]
hello, could you solve that?

**Comment by DigvijayJaswal** [comment]
try **brew install zmq** it worked for me

**Comment by aserg24** [comment]
I had the same problem.
I decided not to install zmq directly since it is installed with Anaconda, so I 
`export PKG_CONFIG_PATH="/home/alena/anaconda3/lib/pkgconfig"`
And this problem is gone, but there was another:
```
$ gophernotes
gophernotes: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
```

**Comment by cosmos72** [comment]
On Mac OS X, the preferred way to install `zmq` is `brew install zmq` as stated in https://zeromq.org/download/

If you install `zmq` in some other way, you may encounter difficulties:
* when compiling gophernotes, you may need to set and export the `PKG_CONFIG_PATH` environment variable to the absolute path of the directory containing `libzmq.pc`
* when starting jupyter and/or gophernotes, you may need to set and export the  `DYLD_LIBRARY_PATH` environment variable - or better `DYLD_FALLBACK_LIBRARY_PATH` - to the absolute path of the directory containing `libzmq.so.5`
